Fix exception messages.
Exception messages in definitions of dbms_stats.restore(bid, relname,
colname) were incorrect. This causes incomprehensive message like this,

ERROR:  too many parameters specified for RAISE

There's no harm other than the bogus message.